apiVersion: v1
kind: Namespace
metadata:
  name: guam
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: pfcjeong/guam-gateway:latest
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
