apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guam
  namespace: argocd
spec:
  description: Guam Project
  sourceRepos:
    - 'https://github.com/wafflestudio/k8s-study'
  destinations:
    - namespace: guam
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  orphanedResources:
    warn: false
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: guam
  namespace: guam
spec:
  hard:
    requests.cpu: 250m
    limits.cpu: 250m
    requests.memory: 512Mi
    limits.memory: 512Mi